# Generated by Django 5.0.1 on 2024-02-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=8)),
            ],
        ),
    ]
